blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index_view"),
    # a link to all the posts that have <category> in their set of categories 
    path('hashtag/<category>', views.CategoryIndexView.as_view(), name="category_index_view"),
    # a link to a specific post whose slug=<slug> 
    path('<slug>', views.PostDetailView.as_view(), name='post_detail_view'),  
    path('unsubscribe/all-posts-on-voila', views.unsubscribe_from_all_posts, name="unsubscribe_from_all_posts_view"),
    # a link to unsubscribe from the comment whose id=<comment_id>
    # so that the commenter no longer recieve email notifications
    # when someone replies to their comment
    path('unsubscribe/<comment_id>', views.unsubscribe_from_comment, name="unsubscribe_from_post_view"),
]

voila/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.base_view, name="base_view"),
    path('projects/', include('projects.urls')),
    path('blog/', include('blog.urls')),
]

handler404 = views.page_not_found

blog/models.py
from django.db import models
from django.urls import reverse
  
class Post(models.Model):
    title    = models.CharField(max_length=120)
    body     = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    # each post has a set of categories 
    categories = models.ManyToManyField('Category',
                                         related_name= 'posts')
    slug = models.SlugField(null=True)

    def __str__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse('blog:post_detail_view', kwargs={'slug': self.slug})    

class Comment(models.Model):
    name  = models.CharField(max_length=60)
    email = models.EmailField()
    comment  = models.TextField()
    # each comment has a post object which it belogs to.
    post = models.ForeignKey('Post', 
                              null=True, 
                              on_delete=models.CASCADE)                         
    created_on = models.DateTimeField(auto_now_add=True)
    # when it's a reply parent_comment must hold the parent comment's id,
    # it's null when it's a comment, not a reply.
    parent_comment = models.ForeignKey('self', 
                                        null=True, 
                                        blank=True, 
                                        related_name='replies', 
                                        on_delete=models.CASCADE,)
    # each comment has a list of recipients so when someone one comments on a post.
    # they get added to the recipients list so that they get notified,
    # when someone replies to thier comment,
    recipients = models.ManyToManyField('Recipient', 
                                        related_name= 'comments',) 

    class Meta:
        ordering = ('created_on',)
     
    def __str__(self):
        return self.comment

class Recipient(models.Model):
    recipient_email = models.EmailField()

    def __str__(self):
        return self.recipient_email

class Category(models.Model):
    name = models.CharField(max_length=60)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:category_index_view', kwargs={'category':self.name})    
  

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
       model = Comment
       fields = ('name', "email", "comment")

       widgets ={
           "name": forms.TextInput(attrs={"id": "comment-author", "placeholder":" Name", "class":"custom-border"}),
           "email": forms.EmailInput(attrs={"id": "comment-email", "placeholder":" email@example.com", "class":"custom-border"}),
           "comment": forms.Textarea(attrs={"id": "comment-textarea", "placeholder":" Leave a comment!", "class":"custom-border"}),
       }

class ReplyForm(forms.ModelForm):
    class Meta:
       model = Comment
       fields = ("name", 'email', "comment",)

       widgets ={
           "name": forms.TextInput(attrs={"id": "reply-author", "placeholder":" Name", "class":"custom-border",}),
           "email": forms.EmailInput(attrs={"id": "reply-email", "placeholder":" email@example.com", "class":"custom-border",}),
            "comment": forms.Textarea(attrs={"id": "reply-textarea", "placeholder":"Your reply here!", "class":"custom-border", }),
       }

class UnsubscribeForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'id': 'email-input', "placeholder":" email@example.com"}))    

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Post, Comment, Recipient
from .forms import CommentForm, ReplyForm, UnsubscribeForm
from django.http import HttpResponse
from django.contrib import messages
from django.core.mail import EmailMultiAlternatives, get_connection, send_mail
from django.template import loader
from voila.settings import VOILA_HOST, MY_EMAIL as my_email

class IndexView(generic.ListView):
    template_name = 'blog/blog-index.html'
    context_object_name = 'posts'
    model = Post
    paginate_by = 5
    def get_queryset(self):
        ''' Return all the posts on blog ordered from newest to oldest '''
        return Post.objects.all().order_by('-pub_date')

class CategoryIndexView(generic.ListView):
    template_name = 'blog/category-index-view.html'
    context_object_name = 'posts'
    model = Post
    paginate_by = 5
    def get_queryset(self):
        '''Return every post that has <category> in its set of categories ordered from newest to oldest'''
        category = self.kwargs['category']
        return Post.objects.filter(categories__name__iexact = category).order_by('-pub_date')

class PostDetailView(generic.DetailView):
    model = Post
    template_name = "blog/post-detail.html"
    comment_form, reply_form = CommentForm(), ReplyForm()

    def get_queryset(self, **kwargs):
        ''' Return the post where post.slug=slug''' 
        slug = self.kwargs.get('slug')
        queryset = Post.objects.filter(slug=slug)
        return queryset

    def get_context_data(self, *args, **kwargs):
        ''' Return context to be passed to a template '''  
        post = self.get_queryset(**kwargs)[0]
        comments = Comment.objects.filter(post=post).order_by('created_on')
        comments_count = comments.count()
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['comments'] = comments
        context['comments_count'] = comments_count
        context['comment_form'] = self.comment_form
        '''A reply form only exists if there's at least one comment on the post.'''
        if comments_count:
           context['reply_form']  = self.reply_form
        return context

    def post(self, request, *args, **kwargs):
        ''' Hadnel the http POST method '''  
        post = self.get_queryset(**kwargs)[0]
        self.object = self.get_object()  
        comment_form = CommentForm(request.POST)
        
        if comment_form.is_valid():
            name = comment_form.cleaned_data["name"]
            email = comment_form.cleaned_data["email"]
            comment_msg= comment_form.cleaned_data["comment"]

            # check if it's a comment form or a reply form
            try:           
               parent_comment_id = int(request.POST.get('parent_comment_id'))
            except: 
               # it's a comment with no replies because the hidden input parent_comment_id wasn't submitted   
               parent_comment_id = None  
                
           
            if parent_comment_id:  # it's a reply because it has a parent id
               reply_form = ReplyForm(request.POST)
               self.save_valid_form(name, email, comment_msg, post, parent_comment_id)  
            else:
               self.save_valid_form(name, email, comment_msg, post)     
        
        return render(request, self.template_name, self.get_context_data(**kwargs))  
        
    def save_valid_form(self, name, email, comment_msg, post, parent_comment_id=None):
        comment = Comment(name=name,
                          email= email,
                          comment=comment_msg,
                         )
        if not parent_comment_id:
            # it's a comment and a comment must belong to a post
            # so we are adding it to the current post
            comment.post = post
            comment.save()
            # and we're also adding the commenter to the recipient list of the comment
            self.add_new_recipient(comment, email) 
            # An email message will be sent to my_email whenever someone comments on a post
            message = f"Someone commented on {post.get_absolute_url()}"
            send_mail("A new comment from Voila", message, my_email, [my_email], fail_silently=False)
        else:
            # when it's a reply we need to know to which comment this reply belongs
            parent_comment = Comment.objects.get(id=parent_comment_id)  
            comment.parent_comment = parent_comment 
            set_of_recipients = set(
                 recipient.recipient_email for recipient in parent_comment.recipients.all() if recipient.recipient_email != email
            )      
   
            if set_of_recipients:
                self.notify_recipients_of_new_reply(set_of_recipients, post, name, parent_comment_id)

            if email not in parent_comment.recipients.all():
                self.add_new_recipient(parent_comment, email)  

            comment.save()
            parent_comment.replies.add(comment) 

            #if not parent_comment.replies.all or not Comment.objects.all:
               # Recipient.objects.filter(recipient_email__contains="@").delete() 

    def add_new_recipient(self, parent_comment, email):
        '''Add new recipients to comments for possible future email notifications'''
        recipient = Recipient(recipient_email=email)
        recipient.save()
        parent_comment.recipients.add(recipient)  
                      
    
    def notify_recipients_of_new_reply(self, set_of_recipients, post, name, parent_comment_id):
        '''Send email notifications to all the people on the comment's recipients list'''

        subject = "A new reply from Voila"
        html_template = loader.get_template('blog/email-template.html')
        context = {
            "name": name,
            "post": post,
            "comment_id": parent_comment_id,
            "VOILA_HOST": VOILA_HOST,
        }
        text_content = "Someone replied to your comment."
        html_content = html_template.render(context)
        messages = []
        for recipient in set_of_recipients:
            msg = EmailMultiAlternatives(subject, text_content, my_email, [recipient])
            msg.attach_alternative(html_content, "text/html")
            messages.append(msg)
        return get_connection().send_messages(messages) 

def unsubscribe_from_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    email = unsubscribe(request)
    if email: 
        if comment.recipients.filter(recipient_email=email):
           # if a valid email and belongs to the recipients list of this comment
           # delete it
           comment.recipients.filter(recipient_email=email).delete() 
           return rerender_or_success(request,"success")
        else:
           # else: display an error message to let the user know that
           # the email they entered doesn't belong to the recipients list of this comment 
           messages.error(request, "The email you entered is not subscribed to any post.")
   
    return rerender_or_success(request,"rerender") 

def unsubscribe_from_all_posts(request):
    email = unsubscribe(request)
    if email:
       if email in [recipient.recipient_email for recipient in Recipient.objects.all()]:
           # if a valid email and an object of Recipient model, delete it
          Recipient.objects.filter(recipient_email=email).delete() 
          return rerender_or_success(request,"success") 
       else:
           messages.error(request, "The email you entered is not subscribed to any post.")  

    return rerender_or_success(request, "rerender")       

def unsubscribe(request): 
    if request.method == "POST":
        unsubscribe_form = UnsubscribeForm(request.POST)
        if unsubscribe_form.is_valid(): 
           recip_email = unsubscribe_form.cleaned_data['email'].lower() 
           return recip_email   

def rerender_or_success(request, msg):
    if msg == "success":
       return render(request, "blog/successfully-unsubscribed.html")
    else:
       return render(request, "blog/unsubsribe-email.html", {"unsubscribe_form": UnsubscribeForm()}) 
   

blog/templates/blog/blog-index.html
{% extends 'base.html' %}
{% load static %}
{% block css_link %}<link rel="stylesheet" href="{% static 'blog-css/blog-index.css' %}" type="text/css" media="screen">{% endblock %}
{% block title %} Broken Magic Wand {% endblock %}
{% block empty_content %}{% endblock %}
{% block main_content %}

<div id="header-img">
  <img src="{% static 'images/magic-wand.png' %}">
</div>

{% block add_things %}{% endblock %}
{% if posts.all %}
{% for post in posts %}
<div class="container post box-shadow">
  <div id="post-title">
     <h2><a href="{{ post.get_absolute_url }}"><code>{{post.title}}</code></a></h2> 
     <h6 id="pub_date">Published on: {{ post.pub_date.date }}</h6>
     <hr>
  </div>
  <div id="post-body">
<p><span id="first-character">{{post.body|slice:"0:1"}}</span>{{ post.body | slice:"1:400" }}...<a href="{{post.get_absolute_url}}">Continue reading.</a></p> 
</div>
<hr>
<div id="post-categories"> 
     {% for category in post.categories.all %}
     &nbsp;<a href="{{ category.get_absolute_url }}">#{{ category.name }} &ensp;</a>
      {% endfor %}   
</div>
</div>
{% endfor %}  
{% else %}
  <div id="empty-content" class="container">
    <p>Sorry, the posts you're looking for don't exist.</p>
  </div>
{% endif %}
{% endblock %}

blog/templates/blog/category-index-view.html
{% extends 'blog/blog-index.html' %}
{% block title %} All #{{ request.path|slice:'14:' }} posts {% endblock %}
{% block add_things %}
<div id="" class="container text-center">
    <h3><code class="text-secondary">All posts for hashtag "{{ request.path|slice:'14:' }}"</code></h3><br>
</div>
{% endblock %}

blog/templates/blog/email-template.html
<!DOCTYPE html>
<html>
<head>  
<style>
a{ 
    text-decoration: none;  
    color: rgb(41, 123, 173);
}
a:hover{
    text-decoration: underline;
}
#wrapper{
    margin-top: 20px;
}
</style>
</head> 
<body>
<div id="wrapper">
    <div id="top">  
    <span id="name">{{name}}</span> has replied to your comment on <a href="{{VOILA_HOST}}{{ post.get_absolute_url }}"><span id="title">{{post.title}}</span></a> 
    on <a href="{{VOILA_HOST}}">Voila</a>
    </div>  
    <div id="middle">
        <br>
    To prevent the website form notifying you of new replies to that comment, please,
    <a href="{{VOILA_HOST}}{% url 'blog:unsubscribe_from_post_view' comment_id %}">unsubscribe</a>.
    Or if you wish to never recieve email notifications from this website <a href="{{VOILA_HOST}}{% url 'blog:unsubscribe_from_all_posts_view' %}">
        click here</a>.
    </div>    
    <br>
     
</div>
</body>
</html>

blog/templates/blog/post-detail.html
{% extends 'base.html' %}
{% load static %}

{% block css_link %}
<link rel="stylesheet" href="{% static 'blog-css/blog-index.css' %}" type="text/css" media="screen">
<link rel="stylesheet" href="{% static 'blog-css/post-detail.css' %}" type="text/css" media="screen">
{% endblock %}
{% block title %} {{post.title}} {% endblock %}
{% block main_content %}

<div class="container" id="post-area">
   <div id="post-title">
    <h2><code>"{{post.title}}"</code></h2><h6 id="pub_date">Published on: {{ post.pub_date.date }}</h6>
    <hr>
   </div>
   <div id="post-body">
    <p><span id="first-character">{{post.body|slice:"0:1"}}</span>{{ post.body | slice:"1:"|linebreaksbr }}</p> 
   </div>

   <hr>
    <div id="post-categories">
       {% for category in post.categories.all %}
           &nbsp;<a href="{{ category.get_absolute_url }}"> #{{category.name }} &nbsp;</a>
      {% endfor %} 
       
    </div>
    <div id="comments-area">
   <div id="show-comments-area">
   {% if comments_count %}
   <div>
       <h6 id="show-comments">Comments({{comments_count}})</h6>
   </div>
   {% endif %}
   <div id="comments">

    {% for comment in comments.all%}
       <div id="commenter-name">{{ comment.name }}</div>
       <div id="comment-body">{{comment.comment}} <br><small>{{ comment.created_on|timesince }} ago.</small>
       {% for reply in comment.replies.all %}
          <div class="ml-3" id="replies-area">
             <div id="reply-name"><small><b>{{reply.name}}</b></small></div>
             <div class="ml-4 reply-color">{{reply.comment}}</div>
             <div class="ml-4 reply-color"><small>{{ reply.created_on|timesince}} ago.</small></div>
          </div>
       {% endfor %}    
     
<!---------------------Reply Form-->
<div class="navbar-toggler" data-toggle="collapse" data-target="#comment{{comment.id}}" aria-controls="comment{{comment.id}}"
     aria-expanded="false" aria-label="Toggle navigation">
     <h6 id="reply">Reply</h6>
</div>
<div id="comment{{comment.id}}" class="collapse reply-form">
   <form method="post" class="">
      {% csrf_token %}
        <label for="reply-author">Name</label>&nbsp;
        {{reply_form.name}} <br>
        <label  for="reply-email">Email</label>  &nbsp; 
        {{reply_form.email}}<br>
        <label for="reply-textarea">Reply </label> &nbsp;
        {{reply_form.comment}}<br>
      <input type="hidden" name="parent_comment_id" value="{{comment.id}}">
      <input type="submit" id="reply-btn" value="Reply">
   </form>
  </div> 
</div> 
<!---------------> 
    {% endfor %}
   </div> 
</div>
   <div id="comment-form" >
      <form action="{{ post.get_absolute_url }}" method="post" class="form">
         {% csrf_token %}
         <div class="input-div">
           <label for="comment-author">Name</label>&nbsp; &nbsp; &nbsp; &nbsp;
           {{comment_form.name}} <br>
           <label  for="comment-email">Email</label>  &nbsp; &nbsp; &nbsp; &nbsp;
           {{comment_form.email}}<br>
           <label for="comment-textarea">Comment </label> 
           {{comment_form.comment}}<br>
        </div> 
         <input type="submit" id="comment-btn" value="Comment">
      </form>
     </div> 
</div> 
</div>
{% endblock %}

blog/templates/blog/successfully-unsubscribed.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<link rel="stylesheet" href="{% static 'blog-css/successfully-unsubscribed.css' %}">
<link href="{% static 'images/favicon.ico' %}" rel="icon" type="image/x-icon" />
<title>Successfully unsubscribed</title>
</head>
<body>
<div style="margin-top: 15px;">
<h3>Your email has been successfully unsubscribed.<br> Thank you so much for being part of my project. <br> It was a pleasure. <br> -- Hajar </h3>
</div>
</body>
</html>

blog/templates/blog/unsubsribe-email.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<link rel="stylesheet" href="{% static 'blog-css/unsubsribe-email.css' %}">
<link href="{% static 'images/favicon.ico' %}" rel="icon" type="image/x-icon" />
<title>Unsubscribe</title>
</head>
<body>
<div id="wrapper">
<h2>Please, enter your email to unsubscribe!</h2>
<form method="post">
    {% csrf_token %}
   {{ unsubscribe_form }}<br><br>
  <input type="submit" value="Submit" id="submit">
</form>
{% if messages %}
<div id="error-msg">
    {% for message in messages %}
    {{ message }}
    {% endfor %}
</div>
{% endif %}
</div>
</body>
</html>