blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index_view"),
    # a link to all the posts that have <category> in their set of categories 
    path('hashtag/<category>', views.CategoryIndexView.as_view(), name="category_index_view"),
    # a link to a specific post whose slug=<slug> 
    path('<slug>', views.PostDetailView.as_view(), name='post_detail_view'),  
    path('unsubscribe/all-posts-on-voila', views.unsubscribe_from_all_posts, name="unsubscribe_from_all_posts_view"),
    # a link to unsubscribe from the comment whose id=<comment_id>
    # so that the commenter no longer recieve email notifications
    # when someone replies to their comment
    path('unsubscribe/<comment_id>', views.unsubscribe_from_comment, name="unsubscribe_from_post_view"),
]

projects/urls.py
from django.urls import path
from . import views

app_name = "projects"
urlpatterns =[
    path('', views.projects_index, name="projects_index")
]

voila/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.base_view, name="base_view"),
    path('projects/', include('projects.urls')),
    path('blog/', include('blog.urls')),
]

handler404 = views.page_not_found

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head> 
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="x-ua-compatible" content="=ie=edge">
        <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https:cdnjs.cloudflare.com/ajax/libs/tether/1.3.1/css/tether.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css" media="screen">
        <link href="https://fonts.googleapis.com/css?family=Patrick+Hand|Frijole|Cabin+Sketch|Bad Script|Itim|Fredericka+the+Great|Pattaya|Material+Icons" rel="stylesheet">
        <link href="{% static 'images/favicon.ico' %}" rel="icon" type="image/x-icon" />
        {% block css_link %}{% endblock %}
        <title> {% block title %} Voila {% endblock %}</title> 
    </head> 
    <body>
      <div class="container-fluid" id="wrapper">
        <div class="container-fluid">
            <nav class="navbar navbar-expand-md fixed-top" id="nav">
              <div class="container">
                <div id="logo"><a class="navbar-brand" href="{% url 'base_view' %}"><h2>Voila</h2></a></div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span><i class="fa fa-bars" id="bars"></i></span>
                </button>
                <div class="collapse navbar-collapse col-xs-8 col-md-5" id="navbarSupportedContent">
                  <ul class="navbar-nav flex-row justify-content-around" id="nav-ul">
                    <li class="nav-item active">
                      <a class="nav-link border border-top-0 border-right-0" href="{% url 'blog:index_view' %}">Blog</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link  border border-bottom-0 border-left-0 border-right-0" href="{% url 'projects:projects_index' %}">Projects</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link  border border-top-0 border-right-0 border-left-0" href="{% url 'base_view' %}#contact-section">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link border border-bottom-0 border-left-0"   href="{% url 'base_view' %}#about-section">About</a>
                    </li>
                    
                  </ul>
                </div>
              </div>  
              </nav>
        </div>
            {% block main_content %}
            <!------------------------------------------voila-section---------------------------------------------->
            <section id="voila">
               <div id ="voila-img">
                 <img src="{% static 'images/06.png'  %}">
               </div>
               <div id="hello-div"class="display-1"><h1>HELLO, ANYBODY THERE!</h1></div>
               <!--
               <div id="goto-blog-arrow">
                 <a href="{% url 'blog:index_view' %}"><h5>Go to blog&nbsp;</h5></a>
                 <i class="fa fa-long-arrow-right"></i>
                </div>
                -->
            </section>
            <!------------------------------------------contact-section---------------------------------------->
            <section id="contact-section" >
               <div id="contact-outer-div" >
                 <div id="contact-inner-left">
                   <div id="contact-words">
                        <h1 class="font">Hello.</h1>
                        <h2 class="font">Hi.</h2>
                        <h3 class="font">Hey.</h3>
                        <h4 class="font">Write me something.</h4>
                        <h4 class="font">Make my day.</h4>
                   </div>
                 </div>
                 <div id="contact-inner-right">
                      <form id="contact-form" method="POST">
                        {% csrf_token %}
                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                          <label class="mdl-textfield__label" for="name">Name</label>
                          {{form.name}}
                        </div>
                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                          <label class="mdl-textfield__label" for="email">Email</label>
                          {{form.email}}
                        </div>
                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label"> 
                          <label for="textarea"class="mdl-textfield__label">Message</label>
                          {{form.message}}
                        </div> 
                        <input type="submit" id="send" value="Send Email">
                      </form>
                 </div>
               </div>
               <br>
            </section>
            <span class="anchor" id="about-section"></span> 
             <!------------------------------------------about-section----------------------------------------------->
             
             <section id="about">
              <div id="absolute-div"></div>
              <div class="container-fluid" id="two-squares">
                <div id="bio">
                     <hr class="hr">
                     <div>
                     <div id="hi"><h1>Hi,</h1></div>
                     <div id="i-am"><p>I am Hajar form Egypt. Still at the beginning of my journey of learning to
                       code. And this is a project I made for the <a href="https://www.100daysofcode.com/">100DaysOfCode</a> challenge.
                       I hope you're having a good day and thank you so much for being here.
                     </p></div>
                    </div>
                     <hr class="hr">
                     <h5 class="social-links"><a href="https://twitter.com/pywings" data-toggle="tooltip" data-placement="top"
                        title="My twitter account" id="tooltip-top"><li class="fa fa-twitter"></li></a></h5>
                </div>
                <div id="tech">
                  
                  <h2><br>Used Technologies</h2>
                  <div id="front-and-end">
                  <div>
                    <h3>Front End</h3>
                    <ul>
                      <li>HTML5</li>
                     <li>CSS3</li>
                     <li>BootStrap</li>
                     <li>MDL</li>
                   </ul>
                </div>
                <div>
                  <h3>Back End</h3>
                  <ul>
                    <li>Python</li>
                    <li>Django</li>
                  </ul>
                </div>
                </div>
                <hr class="hr">
                <h5 class="social-links" data-toggle="tooltip" data-placement="top" title="My messy code">
                  <a href="https://github.com/hajarNasr/Voila"><li class="fa fa-github"></li></a></h5>
              </div>
            </section>
            <!---------------------------------------------------------------------------------------------->
            {% endblock %}
            {% block pagination %}
            {% if is_paginated %}
                  <div id="pagination">
                      <div class="pagination">
                          <span class= "page-links">
                              {% if page_obj.has_previous %}
                                 <a href="{{ request.path }}?page={{ page_obj.previous_page_number}}">
                                  <i class="fa fa-long-arrow-left"></i></a> &nbsp;&emsp;
                              {% endif %}
                              <span class="page-current">
                                   Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages}} &emsp;
                              </span> 
                              {% if page_obj.has_next %}
                                 <a href="{{ request.path }}?page={{ page_obj.next_page_number }}"> 
                                 <i class="fa fa-long-arrow-right"></i></a>
                             {% endif %}   
                          </span>
                      </div>
                  </div>
                  {% endif %}
            {% endblock %}
            <!------------------------------------------footer------------------------------------------------------->
              <footer id="footer">
              <h6>voila&copy;2020</h6>
              <div id="img-srcs">
                <h6>img-sources</h6>
                <ul>
                  <li><a href="https://absurd.design/">Absurd Design</a></li> | 
                  <li><a href="https://undraw.co/">Undraw</a></li> |
                  <li><a href="https://www.canva.com/">Canva</a></li>
                </ul>
              </div>
            </footer>
        </div>
         <!--------------------------------------------JQuery and BootStrap------------------------------------------->
         <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
         <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
         <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
         <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
         <script type="text/javascript">
          $(function () {
              $("[data-toggle='tooltip']").tooltip();
          });

      </script>
    </body> 
</html>

templates/thanks-for-your-email.html
{% load static %}
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="x-ua-compatible" content="=ie=edge">
        <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https:cdnjs.cloudflare.com/ajax/libs/tether/1.3.1/css/tether.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'css/thx-for-your-email.css' %}" type="text/css" media="screen">
        <link href="https://fonts.googleapis.com/css?family=Frijole|Cabin+Sketch|Bad Script|Itim|Fredericka+the+Great|Pattaya|Material+Icons" rel="stylesheet">
        <link href="{% static 'images/favicon.ico' %}" rel="icon" type="image/x-icon" />
        <title>Thank You</title>
    </head>
    <body>
        <div class="container-fluid" id="wrapper">
            <div id="left">
                <div id="thankyou-message">
                   <p> OH MY, someone has actually sent me something!!! 
                    Thank you so much, <span id="name">{{name}}</span>, for making my day. You're the best.</p>
                   <br> 
                </div>
                <div id="link">
                    <a href="{% url 'base_view' %}">Back to voila</a>
                </div>
            </div>
            <div id="right"></div>
        </div>
        <!--------------------------------------------JQuery and BootStrap------------------------------------------->
        <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>
</html>